try:
    a = 20 / 0
except Exception as e:
    print("Error Occured in try block",e)